namespace ResourceLib
{
    /// <summary>
    ///     字符枚举
    /// </summary>
    public enum TextType
    {
        UseDefaultLanguage,

        Main_Tab_Tree,
        Main_Tab_Table,
        Main_Tab_Text,
        Main_StatusBar_Text_Ready,

        AddConnection_Title,
        AddConnection_ConnectionName,
        AddConnection_Name_Description,
        AddConnection_Host_Description,
        AddConnection_Port_Description,
        AddConnection_UserName_Description,
        AddConnection_Password_Description,
        AddConnection_DBName,
        AddConnection_DBName_Description,
        AddConnection_MainReplsetName,
        AddConnection_MainReplsetName_Description,
        AddConnection_Priority,
        AddConnection_SocketTimeOut,
        AddConnection_ConnectionTimeOut,

        AddConnection_MasterSlave,
        AddConnection_SafeMode,
        AddConnection_ShardingSvrType,
        AddConnection_ServerType_Data,
        AddConnection_ServerType_Configuration,
        AddConnection_ServerType_Route,
        AddConnection_ServerType_Arbitration,

        AddConnection_Region_ReplaceSet,
        AddConnection_Region_ReplaceSetName,
        AddConnection_Region_ReplaceSetName_Description,
        AddConnection_Region_ReplaceSetList,
        AddConnection_Region_AddHost,
        AddConnection_Region_RemoveHost,
        AddConnection_ConnectionString,
        AddConnection_Attention_Description,
        AddConnection_Attention2_Description,

        CollectionIndex_Title,
        CollectionIndex_Tab_Current,
        CollectionIndex_Tab_Current_Del,
        CollectionIndex_Tab_Manager,

        Connect_Title,
        Connect_Action_Del,
        Connect_Action_Cancel,

        ConvertSql_Title,

        Distinct_Action_LoadQuery,
        Distinct_SelectField,

        DosCommand_Tab_Deploy,
        DosCommand_Tab_Deploy_Authentication,
        DosCommand_Tab_Deploy_MasterAddress,
        DosCommand_Tab_Deploy_Port,
        DosCommand_Tab_Deploy_Master,
        DosCommand_Tab_Deploy_Slave,
        DosCommand_Tab_Deploy_SlaveSource,
        DosCommand_Tab_Deploy_DBPath,
        DosCommand_Tab_Deploy_LogPath,
        DosCommand_Tab_Deploy_Log,
        DosCommand_Tab_Deploy_AppendMode,
        DosCommand_Tab_Backup,
        DosCommand_Tab_Backup_Server,
        DosCommand_Tab_Backup_Port,
        DosCommand_Tab_Backup_DBName,
        DosCommand_Tab_Backup_DCName,
        DosCommand_Tab_Backup_Path,
        DosCommand_Tab_ExIn,
        DosCommand_Tab_ExIn_Server,
        DosCommand_Tab_ExIn_Port,
        DosCommand_Tab_ExIn_DBName,
        DosCommand_Tab_ExIn_DCName,
        DosCommand_Tab_ExIn_ColumnList,
        DosCommand_Tab_ExIn_Workfile,
        DosCommand_Tab_ExIn_Import,
        DosCommand_Tab_ExIn_Export,
        DosCommand_Tab_ExIn_Operation,
        DosCommand_Run,
        DosCommand_Browse,
        DosCommand_Clean,
        DosCommand_LogLevel,

        EvalJS_Title,
        EvalJS_Method,
        EvalJS_Run,
        EvalJS_Parameter,

        Group_Tab_Reduce,
        Group_Tab_Finalize,
        Group_Tab_Group,
        Group_Tab_Group_Notes,
        Group_Tab_InitColumn,
        Group_Tab_InitColumn_Note,
        Group_Tab_Result,
        Group_LoadQuery,

        //Option
        Option_Title,
        Option_BinPath,
        Option_Language,
        Option_RecordPerPage,
        Option_RefreshInterval,

        //MapReduce
        MapReduce_MapFunction,
        MapReduce_ReduceFunction,
        MapReduce_Result,
        MapReduce_Run,

        Query_Title,
        Query_Filter,
        Query_Filter_AddCondition,
        Query_FieldInfo,
        Query_Action_Load,

        Replset_Title,
        Replset_AddServer,
        Replset_RemoveServer,
        Replset_Remove,
        Replset_InitReplset,

        ServiceStatus_Title,
        ServiceStatus_ServerInfo,
        ServiceStatus_DataBaseInfo,
        ServiceStatus_CollectionInfo,
        ServiceStatus_CurrentOperationInfo,

        ShardingConfig_Title,
        ShardingConfig_AddSharding,
        ShardingConfig_ReplsetName,
        ShardingConfig_EnableSharding,
        ShardingConfig_DBName,
        ShardingConfig_CollectionName,
        ShardingConfig_FieldName,
        ShardingConfig_Action_DBSharding,
        ShardingConfig_Action_CollectionSharding,

        //Controller
        ctlIndexCreate_Index,
        ctlIndexCreate_Description,
        ctlFieldInfo_Show,

        //GFS
        GFS_filename,
        GFS_length,
        GFS_chunkSize,
        GFS_uploadDate,
        GFS_md5,
        GFS_Insert_Option_RemoteFileName,
        GFS_Insert_Option_OnlyFilename,
        GFS_Insert_Option_FullPath,
        GFS_Insert_Option_FileAlreadyExist,
        GFS_Insert_Option_JustAddIt,
        GFS_Insert_Option_Rename,
        GFS_Insert_Option_SkipIt,
        GFS_Insert_Option_Overwrite,
        GFS_Insert_Option_Stop,
        GFS_Insert_Option_IngoreSubFolder,
        GFS_Insert_Option_DirectorySeparatorChar,

        //DataBase_Status
        DataBase_Status_DataBaseName,
        DataBase_Status_CollectionCount,
        DataBase_Status_DataSize,
        DataBase_Status_FileSize,
        DataBase_Status_IndexCount,
        DataBase_Status_IndexSize,
        DataBase_Status_ObjectCount,
        DataBase_Status_StorageSize,

        //Collection_Status
        Collection_Status_CollectionName,
        Collection_Status_ObjectCount,
        Collection_Status_DataSize,
        Collection_Status_LastExtentSize,
        Collection_Status_StorageSize,
        Collection_Status_TotalIndexSize,
        Collection_Status_AverageObjectSize,
        Collection_Status_PaddingFactor,
        Collection_Status_MaxDocuments,
        Collection_Status_MaxSize,
        Collection_Status_IsCapped,
        Collection_Status_IsAutoIndexId,

        Collection_Resume_AutoRefresh,
        Collection_Stop_AutoRefresh,

        //Index
        Index_Asce,
        Index_Desc,
        Index_NoSort,

        Index_Background,
        Index_RepeatDel,
        Index_Sparse,
        Index_Unify,
        Index_Name,
        Index_Keys,
        Index_Version,
        Index_ExpireData,
        Index_NameSpace,

        //Exception
        Exception_NotConnected,
        Exception_NotConnected_Note,
        Exception_AuthenticationException,
        Exception_AuthenticationException_Note,

        Selected_Server,
        Selected_DataBase,
        Selected_Collection,
        Selected_Data,
        Selected_Indexes,
        Selected_Index,
        Selected_GFS,
        Selected_UserList,

        //MongoUtility
        Common_Username,
        Common_Password,
        Common_ChangePassword,
        Common_ReadOnly,
        Common_OK,
        Common_ConfirmPassword,
        Common_Close,
        Common_Cancel,
        Common_Refresh,
        Common_Yes,
        Common_No,
        Common_Detail,
        Common_Edit,
        Common_Save,
        Common_Save_Local,
        Common_Modify,
        Common_Add,
        Common_Server,
        Common_Connect,
        Common_DataBase,
        Common_Collection,
        Common_Host,
        Common_Port,
        Common_Browse,
        Common_Clear,
        Common_Test,
        Common_Advance_Option,
        Common_Collapse,
        Common_Expansion,
        Common_Name,
        Common_Value,
        Common_Type,
        Common_Roles,
        Common_Validate,
        Common_Search,

        //MessageBox
        Create_New_DataBase,
        Create_New_DataBase_Input,
        Drop_DataBase,
        Drop_DataBase_Confirm,
        Create_New_Collection,
        Rename_Collection,
        Rename_Collection_Input,
        Drop_Collection,
        Drop_Collection_Confirm,
        Drop_User,
        Drop_User_Confirm,
        Drop_Data,
        Drop_Data_Confirm,
        Restore_Connection_Confirm,

        SYSTEMC_COLNAME_chunks,
        SYSTEMC_COLNAME_collections,
        SYSTEMC_COLNAME_changelog,
        SYSTEMC_COLNAME_databases,
        SYSTEMC_COLNAME_lockpings,
        SYSTEMC_COLNAME_locks,
        SYSTEMC_COLNAME_mongos,
        SYSTEMC_COLNAME_settings,
        SYSTEMC_COLNAME_shards,
        SYSTEMC_COLNAME_tags,
        SYSTEMC_COLNAME_version,
        SYSTEMC_COLNAME_me,
        SYSTEMC_COLNAME_sources,
        SYSTEMC_COLNAME_slaves,
        COLLECTION_NAME_GFS_CHUNKS,
        COLLECTION_NAME_GFS_FILES,
        COLLECTION_NAME_OPERATION_LOG,
        COLLECTION_NAME_SYSTEM_INDEXES,
        COLLECTION_NAME_JAVASCRIPT,
        COLLECTION_NAME_SYSTEM_REPLSET,
        COLLECTION_NAME_REPLSET_MINVALID,
        COLLECTION_NAME_USER,
        COLLECTION_NAME_ROLE,
        COLLECTION_NAME_SYSTEM_PROFILE
    }
}