namespace ResourceLib.Method
{
    /// <summary>
    ///     字符枚举
    /// </summary>
    public enum TextType
    {
        UseDefaultLanguage,

        MainTabTree,
        MainTabTable,
        MainTabText,
        MainStatusBarTextReady,
        MainMenuOperationServerAddUserToAdmin,

        AddConnectionTitle,
        AddConnectionConnectionName,
        AddConnectionNameDescription,
        AddConnectionHostDescription,
        AddConnectionPortDescription,
        AddConnectionUserNameDescription,
        AddConnectionPasswordDescription,
        AddConnectionDbName,
        AddConnectionDbNameDescription,
        AddConnectionMainReplsetName,
        AddConnectionMainReplsetNameDescription,
        AddConnectionPriority,
        AddConnectionSocketTimeOut,
        AddConnectionConnectionTimeOut,

        AddConnectionMasterSlave,
        AddConnectionSafeMode,
        AddConnectionShardingSvrType,
        AddConnectionServerTypeData,
        AddConnectionServerTypeConfiguration,
        AddConnectionServerTypeRoute,
        AddConnectionServerTypeArbitration,

        AddConnectionRegionReplaceSet,
        AddConnectionRegionReplaceSetName,
        AddConnectionRegionReplaceSetNameDescription,
        AddConnectionRegionReplaceSetList,
        AddConnectionRegionAddHost,
        AddConnectionRegionRemoveHost,
        AddConnectionConnectionString,
        AddConnectionAttentionDescription,
        AddConnectionAttention2Description,

        CollectionIndexTitle,
        CollectionIndexTabCurrent,
        CollectionIndexTabCurrentDel,
        CollectionIndexTabManager,

        ConnectTitle,
        ConnectActionDel,
        ConnectActionCancel,

        ConvertSqlTitle,

        DistinctActionLoadQuery,
        DistinctSelectField,

        DosCommandTabDeploy,
        DosCommandTabDeployAuthentication,
        DosCommandTabDeployMasterAddress,
        DosCommandTabDeployPort,
        DosCommandTabDeployMaster,
        DosCommandTabDeploySlave,
        DosCommandTabDeploySlaveSource,
        DosCommandTabDeployDbPath,
        DosCommandTabDeployLogPath,
        DosCommandTabDeployLog,
        DosCommandTabDeployAppendMode,
        DosCommandTabBackup,
        DosCommandTabBackupServer,
        DosCommandTabBackupPort,
        DosCommandTabBackupDbName,
        DosCommandTabBackupDcName,
        DosCommandTabBackupPath,
        DosCommandTabExIn,
        DosCommandTabExInServer,
        DosCommandTabExInPort,
        DosCommandTabExInDbName,
        DosCommandTabExInDcName,
        DosCommandTabExInColumnList,
        DosCommandTabExInWorkfile,
        DosCommandTabExInImport,
        DosCommandTabExInExport,
        DosCommandTabExInOperation,
        DosCommandRun,
        DosCommandBrowse,
        DosCommandClean,
        DosCommandLogLevel,

        EvalJsTitle,
        EvalJsMethod,
        EvalJsRun,
        EvalJsParameter,

        GroupTabReduce,
        GroupTabFinalize,
        GroupTabGroup,
        GroupTabGroupNotes,
        GroupTabInitColumn,
        GroupTabInitColumnNote,
        GroupTabResult,
        GroupLoadQuery,

        //Option
        OptionTitle,
        OptionBinPath,
        OptionLanguage,
        OptionRecordPerPage,
        OptionRefreshInterval,

        //MapReduce
        MapReduceMapFunction,
        MapReduceReduceFunction,
        MapReduceResult,
        MapReduceRun,

        QueryTitle,
        QueryFilter,
        QueryFilterAddCondition,
        QueryFieldInfo,
        QueryActionLoad,

        ReplsetTitle,
        ReplsetAddServer,
        ReplsetRemoveServer,
        ReplsetRemove,
        ReplsetInitReplset,

        ServiceStatusTitle,
        ServiceStatusServerInfo,
        ServiceStatusDataBaseInfo,
        ServiceStatusCollectionInfo,
        ServiceStatusCurrentOperationInfo,

        ShardingConfigTitle,
        ShardingConfigAddSharding,
        ShardingConfigReplsetName,
        ShardingConfigEnableSharding,
        ShardingConfigDbName,
        ShardingConfigCollectionName,
        ShardingConfigFieldName,
        ShardingConfigActionDbSharding,
        ShardingConfigActionCollectionSharding,

        //Controller
        CtlIndexCreateIndex,
        CtlIndexCreateDescription,
        CtlFieldInfoShow,

        //GFS
        GfsFilename,
        GfsLength,
        GfsChunkSize,
        GfsUploadDate,
        GfsMd5,
        GfsInsertOptionRemoteFileName,
        GfsInsertOptionOnlyFilename,
        GfsInsertOptionFullPath,
        GfsInsertOptionFileAlreadyExist,
        GfsInsertOptionJustAddIt,
        GfsInsertOptionRename,
        GfsInsertOptionSkipIt,
        GfsInsertOptionOverwrite,
        GfsInsertOptionStop,
        GfsInsertOptionIngoreSubFolder,
        GfsInsertOptionDirectorySeparatorChar,

        //DataBase_Status
        DataBaseStatusDataBaseName,
        DataBaseStatusCollectionCount,
        DataBaseStatusDataSize,
        DataBaseStatusFileSize,
        DataBaseStatusIndexCount,
        DataBaseStatusIndexSize,
        DataBaseStatusObjectCount,
        DataBaseStatusStorageSize,

        //Collection_Status
        CollectionStatusCollectionName,
        CollectionStatusObjectCount,
        CollectionStatusDataSize,
        CollectionStatusLastExtentSize,
        CollectionStatusStorageSize,
        CollectionStatusTotalIndexSize,
        CollectionStatusAverageObjectSize,
        CollectionStatusPaddingFactor,
        CollectionStatusMaxDocuments,
        CollectionStatusMaxSize,
        CollectionStatusIsCapped,
        CollectionStatusIsAutoIndexId,

        CollectionResumeAutoRefresh,
        CollectionStopAutoRefresh,

        //Index
        CopyIndex,

        IndexAsce,
        IndexDesc,
        IndexNoSort,

        IndexBackground,
        IndexRepeatDel,
        IndexSparse,
        IndexUnify,
        IndexName,
        IndexKeys,
        IndexVersion,
        IndexExpireData,
        IndexNameSpace,

        //Exception
        ExceptionNotConnected,
        ExceptionNotConnectedNote,
        ExceptionAuthenticationException,
        ExceptionAuthenticationExceptionNote,

        SelectedServer,
        SelectedDataBase,
        SelectedCollection,
        SelectedData,
        SelectedIndexes,
        SelectedIndex,
        SelectedGfs,
        SelectedUserList,

        //MongoUtility
        CommonUsername,
        CommonPassword,
        CommonChangePassword,
        CommonReadOnly,
        CommonOk,
        CommonConfirmPassword,
        CommonClose,
        CommonCancel,
        CommonRefresh,
        CommonYes,
        CommonNo,
        CommonDetail,
        CommonEdit,
        CommonSave,
        CommonSaveLocal,
        CommonModify,
        CommonAdd,
        CommonServer,
        CommonConnect,
        CommonDataBase,
        CommonCollection,
        CommonHost,
        CommonPort,
        CommonBrowse,
        CommonClear,
        CommonTest,
        CommonAdvanceOption,
        CommonCollapse,
        CommonExpansion,
        CommonName,
        CommonValue,
        CommonType,
        CommonRoles,
        CommonValidate,
        CommonSearch,

        //MessageBox
        CreateNewDataBase,
        CreateNewDataBaseInput,
        DropDataBase,
        DropDataBaseConfirm,
        CreateNewCollection,
        RenameCollection,
        RenameCollectionInput,
        DropCollection,
        DropCollectionConfirm,
        DropUser,
        DropUserConfirm,
        DropData,
        DropDataConfirm,
        RestoreConnectionConfirm,

        SystemcColnameChunks,
        SystemcColnameCollections,
        SystemcColnameChangelog,
        SystemcColnameDatabases,
        SystemcColnameLockpings,
        SystemcColnameLocks,
        SystemcColnameMongos,
        SystemcColnameSettings,
        SystemcColnameShards,
        SystemcColnameTags,
        SystemcColnameVersion,
        SystemcColnameMe,
        SystemcColnameSources,
        SystemcColnameSlaves,
        CollectionNameGfsChunks,
        CollectionNameGfsFiles,
        CollectionNameOperationLog,
        CollectionNameSystemIndexes,
        CollectionNameJavascript,
        CollectionNameSystemReplset,
        CollectionNameReplsetMinvalid,
        CollectionNameUser,
        CollectionNameRole,
        CollectionNameSystemProfile,
        MainMenuMangtStatus,
        MainMenuOperationDatabaseAddUser,
        MainMenuOperationServerUserInfo,
        MainMenuOperationFileSystemDelFile,
        MainMenuOperationFileSystemUploadFile,
        MainMenuOperationFileSystemUploadFolder,
        MainMenuOperationFileSystemDownload,
        MainMenuOperationFileSystemOpenFile,
        MainMenuDataView,
        MainMenuOperationDatabaseDelUser,
        MainMenuOperationServerProperties,
        MainMenuOperationBackupAndRestoreRestore
    }
}